/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReviewId = IDL.Text;
export const UserId = IDL.Text;
export const Timestamp = IDL.Int;
export const ProductId = IDL.Text;
export const Review = IDL.Record({
  'id' : ReviewId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : IDL.Text,
  'productId' : ProductId,
  'rating' : IDL.Nat,
  'helpful' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Cart = IDL.Record({
  'userId' : UserId,
  'updatedAt' : Timestamp,
  'items' : IDL.Vec(CartItem),
});
export const OrderId = IDL.Text;
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : IDL.Text,
  'total' : IDL.Float64,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const Spec = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
export const Product = IDL.Record({
  'id' : ProductId,
  'specifications' : IDL.Vec(Spec),
  'inStock' : IDL.Bool,
  'originalPrice' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
  'reviewCount' : IDL.Nat,
  'isTrending' : IDL.Bool,
  'images' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [Review],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Cart], []),
  'clearCart' : IDL.Func([IDL.Text], [], []),
  'getCart' : IDL.Func([IDL.Text], [IDL.Opt(Cart)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProductReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getProducts' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'placeOrder' : IDL.Func([IDL.Text, IDL.Text], [Order], []),
  'removeFromCart' : IDL.Func([IDL.Text, IDL.Text], [Cart], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReviewId = IDL.Text;
  const UserId = IDL.Text;
  const Timestamp = IDL.Int;
  const ProductId = IDL.Text;
  const Review = IDL.Record({
    'id' : ReviewId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'authorName' : IDL.Text,
    'productId' : ProductId,
    'rating' : IDL.Nat,
    'helpful' : IDL.Nat,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Cart = IDL.Record({
    'userId' : UserId,
    'updatedAt' : Timestamp,
    'items' : IDL.Vec(CartItem),
  });
  const OrderId = IDL.Text;
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : IDL.Text,
    'total' : IDL.Float64,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const Spec = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const Product = IDL.Record({
    'id' : ProductId,
    'specifications' : IDL.Vec(Spec),
    'inStock' : IDL.Bool,
    'originalPrice' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
    'reviewCount' : IDL.Nat,
    'isTrending' : IDL.Bool,
    'images' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [Review],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Cart], []),
    'clearCart' : IDL.Func([IDL.Text], [], []),
    'getCart' : IDL.Func([IDL.Text], [IDL.Opt(Cart)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProductReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getProducts' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'placeOrder' : IDL.Func([IDL.Text, IDL.Text], [Order], []),
    'removeFromCart' : IDL.Func([IDL.Text, IDL.Text], [Cart], []),
  });
};

export const init = ({ IDL }) => { return []; };