/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart {
  'userId' : UserId,
  'updatedAt' : Timestamp,
  'items' : Array<CartItem>,
}
export interface CartItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : number,
}
export interface Order {
  'id' : OrderId,
  'status' : string,
  'total' : number,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'shippingAddress' : string,
  'items' : Array<CartItem>,
}
export type OrderId = string;
export interface Product {
  'id' : ProductId,
  'specifications' : Array<Spec>,
  'inStock' : boolean,
  'originalPrice' : number,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
  'brand' : string,
  'rating' : number,
  'price' : number,
  'reviewCount' : bigint,
  'isTrending' : boolean,
  'images' : Array<string>,
}
export type ProductId = string;
export interface Review {
  'id' : ReviewId,
  'title' : string,
  'body' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : string,
  'productId' : ProductId,
  'rating' : bigint,
  'helpful' : bigint,
}
export type ReviewId = string;
export interface Spec { 'key' : string, 'value' : string }
export type Timestamp = bigint;
export type UserId = string;
export interface _SERVICE {
  'addReview' : ActorMethod<
    [string, string, string, bigint, string, string],
    Review
  >,
  'addToCart' : ActorMethod<[string, string, bigint], Cart>,
  'clearCart' : ActorMethod<[string], undefined>,
  'getCart' : ActorMethod<[string], [] | [Cart]>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrders' : ActorMethod<[string], Array<Order>>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProductReviews' : ActorMethod<[string], Array<Review>>,
  'getProducts' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [string],
    ],
    Array<Product>
  >,
  'placeOrder' : ActorMethod<[string, string], Order>,
  'removeFromCart' : ActorMethod<[string, string], Cart>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];